### ISSUE TITLE
How to do relations?

### ISSUE THREAD

**Issue by ekarlso** [kvesteri/colander-alchemy#3]
How does one use relations?

**Comment by ekarlso** [comment]
Is this not supported anymore or ?

**Comment by kvesteri** [comment]
Yes its supported. Just include them in your **schema** property keys. You can find examples in the tests.

Simple example:

``` python
class Location(Base, ColanderAlchemyMixin):
    __tablename__ = 'location'

    id = sa.Column(sa.BigInteger, autoincrement=True, primary_key=True)
    name = sa.Column(sa.Unicode(255))


class Event(Base, ColanderAlchemyMixin):
    __tablename__ = 'event'

    id = sa.Column(sa.BigInteger, autoincrement=True, primary_key=True)
    name = sa.Column(sa.Unicode(255))
    location_id = sa.Column(sa.BigInteger, sa.ForeignKey(Location.id))
    location = sa.relationship(Location)

    __schema__ = {
        'location': {}
    }
```

**Comment by kvesteri** [comment]
Btw I do not develop this package anymore. I've created two packages for WTForms which give you even more powerful set of tools than what you have with colander.

Please check out: https://github.com/kvesteri/wtforms-json <- this adds JSON handling support for WTForms

And also: https://github.com/kvesteri/wtforms-alchemy <- same as colander-alchemy except the syntax is MUCH nicer

**Comment by ekarlso** [comment]
I just need schema functionality really. JSON api. Does it work for this as
well?
Den 30. aug. 2012 16:01 skrev "Konsta Vesterinen" notifications@github.com
følgende:

**Comment by kvesteri** [comment]
Yes using wtforms-json along with wtforms-alchemy is exactly what our company is using for RESTful JSON APIs right now.

**Comment by kvesteri** [comment]
Please feel free to ask anything about those packages. I will add more documentation for those very soon.

**Comment by ekarlso** [comment]
How to use wtforms packages then ?

Endre :)

2012/8/30 Konsta Vesterinen notifications@github.com

**Comment by ekarlso** [comment]
Are you available on IRC? :)

Endre.

**Comment by kvesteri** [comment]
Yeah, you can find me at irc.freenode.net, my nickname is zYne
